# This file is managed by Qt Creator, do not edit!

set("CMAKE_GENERATOR" "Ninja" CACHE "STRING" "" FORCE)
set("CMAKE_BUILD_TYPE" "Debug" CACHE "STRING" "" FORCE)
set("QT_QMAKE_EXECUTABLE" "/home/avnzx/Qt/6.4.3/android_arm64_v8a/bin/qmake" CACHE "FILEPATH" "" FORCE)
set("CMAKE_PREFIX_PATH" "/home/avnzx/Qt/6.4.3/android_arm64_v8a" CACHE "PATH" "" FORCE)
set("CMAKE_C_COMPILER" "/home/avnzx/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" CACHE "FILEPATH" "" FORCE)
set("CMAKE_CXX_COMPILER" "/home/avnzx/Android/Sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++" CACHE "FILEPATH" "" FORCE)
set("ANDROID_PLATFORM" "android-23" CACHE "STRING" "" FORCE)
set("ANDROID_NDK" "/home/avnzx/Android/Sdk/ndk/25.1.8937393" CACHE "PATH" "" FORCE)
set("CMAKE_TOOLCHAIN_FILE" "/home/avnzx/Android/Sdk/ndk/25.1.8937393/build/cmake/android.toolchain.cmake" CACHE "FILEPATH" "" FORCE)
set("ANDROID_USE_LEGACY_TOOLCHAIN_FILE" "OFF" CACHE "BOOL" "" FORCE)
set("ANDROID_ABI" "arm64-v8a" CACHE "STRING" "" FORCE)
set("ANDROID_STL" "c++_shared" CACHE "STRING" "" FORCE)
set("CMAKE_FIND_ROOT_PATH" "/home/avnzx/Qt/6.4.3/android_arm64_v8a" CACHE "PATH" "" FORCE)
set("QT_NO_GLOBAL_APK_TARGET_PART_OF_ALL" "ON" CACHE "BOOL" "" FORCE)
set("QT_HOST_PATH" "/home/avnzx/Qt/6.4.3/gcc_64" CACHE "PATH" "" FORCE)
set("ANDROID_SDK_ROOT" "/home/avnzx/Android/Sdk" CACHE "PATH" "" FORCE)
set("CMAKE_CXX_FLAGS_INIT" "-DQT_QML_DEBUG" CACHE "STRING" "" FORCE)